# Generated by Django 3.0 on 2020-06-11 16:50

import django.core.files.storage
from django.db import migrations, models
import webapp.fileupload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('image', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/var/hex1e/media/'), upload_to=webapp.fileupload.blog_file_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=1000)),
            ],
        ),
    ]
