# Generated by Django 3.0 on 2020-06-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=50)),
                ('participant_email', models.EmailField(max_length=254)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Raffle')),
            ],
        ),
    ]
