# Generated by Django 3.0 on 2020-06-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_raffle_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_posted']},
        ),
    ]
